apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "shop-backend-chart.fullname" . }}-hello-sre
  labels:
    {{- include "shop-backend-chart.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: hello-sre
              image: "{{ .Values.cronjob.image.repository }}:{{ .Values.cronjob.image.tag }}"
              imagePullPolicy: {{ .Values.cronjob.image.pullPolicy }}
              command: ["sh", "-c", "echo Hello SRE"]
